apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  labels:
    app: users-api
stringData:
  connectionString: "Server=sqlserver;Database=FCGUsers;User Id=sa;Password=pass@123;TrustServerCertificate=True"
  jwtIssuer: "fcg-users"
  jwtKey: "super_secret_dev_key_change_me"
